# Generated by Django 6.0.6 on 2026-07-24 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('total_questions_answered', models.PositiveIntegerField(default=0)),
                ('total_practice_time_seconds', models.PositiveIntegerField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('daily_practice_time_seconds', models.PositiveIntegerField(default=0)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('app_version', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Reporte de Estudiante',
                'verbose_name_plural': 'Reportes de Estudiantes',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_name', models.CharField(max_length=100)),
                ('level_name', models.CharField(max_length=100)),
                ('competence_id', models.PositiveIntegerField()),
                ('level_id', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='core.studentreport')),
            ],
            options={
                'verbose_name': 'Progreso por nivel',
                'verbose_name_plural': 'Progresos por nivel',
            },
        ),
    ]
