# Generated by Django 6.0.6 on 2026-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='academic_program',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Programa Académico'),
        ),
    ]
