# Generated by Django 6.0.6 on 2026-09-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentreport_academic_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='max_streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Mejor racha'),
        ),
    ]
