# Generated by Django 6.0.6 on 2026-09-30 03:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_historicalquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question-context/', verbose_name='Imagen')),
                ('alt_text', models.CharField(help_text='Que se ve en la imagen. Lo lee en voz alta el lector de pantalla, asi que describe el contenido, no el archivo.', max_length=180, verbose_name='Texto alternativo')),
                ('caption', models.CharField(blank=True, help_text='Opcional. Se muestra debajo de la imagen.', max_length=240, verbose_name='Leyenda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen de contexto',
                'verbose_name_plural': 'Imagenes de contexto',
                'ordering': ['alt_text'],
            },
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si se desmarca, la pregunta deja de enviarse a la app sin romper los intentos ya registrados.', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 9, 30, 3, 41, 5, 301669, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Ultima modificacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si se desmarca, la pregunta deja de enviarse a la app sin romper los intentos ya registrados.', verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='context_image',
            field=models.CharField(blank=True, help_text='Obsoleto. Usa el campo de arriba, que admite subir el archivo.', max_length=100, verbose_name='Imagen de contexto (nombre heredado)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='context_image',
            field=models.CharField(blank=True, help_text='Obsoleto. Usa el campo de arriba, que admite subir el archivo.', max_length=100, verbose_name='Imagen de contexto (nombre heredado)'),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='context_asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.contextasset', verbose_name='Imagen de contexto'),
        ),
        migrations.AddField(
            model_name='question',
            name='context_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='academics.contextasset', verbose_name='Imagen de contexto'),
        ),
    ]
