# Generated by Django 6.0.6 on 2026-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_contextasset_historicalquestion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='formato_practica',
            field=models.CharField(choices=[('opcion', 'Elegir una opcion (como en evaluacion)'), ('arrastrar', 'Arrastrar la palabra al hueco'), ('unir', 'Unir parejas')], default='opcion', help_text='Solo se aplica a los niveles de practica (orden 0). En los de evaluacion se ignora: ahi siempre se elige una opcion.', max_length=12, verbose_name='Formato en practica'),
        ),
    ]
